export const MarkData = [
    // {
    //     'part_no': 'XJ112233',
    //     'file_id': '5a4d86e81d99a843a74e938a',
    //     'file_name': 'Example1.txt',
    //     'file_version': '2',
    //     'part_type': '2. Blade Dummy Chassis',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'YZ445566',
    //     'file_id': '6b3e97f42c18b2d1e5f7a2b4',
    //     'file_name': 'Example2.txt',
    //     'file_version': '1',
    //     'part_type': '3. Blade Enclosure Chassis',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'AB778899',
    //     'file_id': '7c1a2b8e3f5d6a9d4a7f2e1b',
    //     'file_name': 'Example3.txt',
    //     'file_version': '3',
    //     'part_type': '5. Blade Server Enclosure',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'CD334455',
    //     'file_id': '8d3e4f6a9b2c7e8d1e5f7a2b',
    //     'file_name': 'Example4.txt',
    //     'file_version': '2',
    //     'part_type': '1. Air Shroud',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'EF556677',
    //     'file_id': '9a8d7e6f5d4a3f2e1b9c8d7e',
    //     'file_name': 'Example5.txt',
    //     'file_version': '1',
    //     'part_type': '4. Blade Module Chassis',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'GH889900',
    //     'file_id': '1b2c3d4e5f6a7b8c9d0e1f2',
    //     'file_name': 'Example6.txt',
    //     'file_version': '3',
    //     'part_type': '3. Blade Enclosure Chassis',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'IJ001122',
    //     'file_id': '2c3d4e5f6a7b8c9d0e1f2g3',
    //     'file_name': 'Example7.txt',
    //     'file_version': '1',
    //     'part_type': '2. Blade Dummy Chassis',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'KL223344',
    //     'file_id': '3d4e5f6a7b8c9d0e1f2g3h4',
    //     'file_name': 'Example8.txt',
    //     'file_version': '2',
    //     'part_type': '5. Blade Server Enclosure',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'MN445566',
    //     'file_id': '4e5f6a7b8c9d0e1f2g3h4i5',
    //     'file_name': 'Example9.txt',
    //     'file_version': '3',
    //     'part_type': '4. Blade Module Chassis',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'OP667788',
    //     'file_id': '5g6a7b8c9d0e1f2g3h4i5j6',
    //     'file_name': 'Example10.txt',
    //     'file_version': '1',
    //     'part_type': '1. Air Shroud',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'QR889900',
    //     'file_id': '6h7b8c9d0e1f2g3h4i5j6k7',
    //     'file_name': 'Example11.txt',
    //     'file_version': '2',
    //     'part_type': '3. Blade Enclosure Chassis',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'ST112233',
    //     'file_id': '7i8c9d0e1f2g3h4i5j6k7l8',
    //     'file_name': 'Example12.txt',
    //     'file_version': '3',
    //     'part_type': '4. Blade Module Chassis',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'UV334455',
    //     'file_id': '8j9d0e1f2g3h4i5j6k7l8m9',
    //     'file_name': 'Example13.txt',
    //     'file_version': '1',
    //     'part_type': '5. Blade Server Enclosure',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'WX556677',
    //     'file_id': '9k7l8m9n0e1f2g3h4i5j6k7l8m9',
    //     'file_name': 'Example14.txt',
    //     'file_version': '2',
    //     'part_type': '1. Air Shroud',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'YZ778899',
    //     'file_id': '0n1e2f3g4h5i6j7k8l9m0n1',
    //     'file_name': 'Example15.txt',
    //     'file_version': '3',
    //     'part_type': '2. Blade Dummy Chassis',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'AB001122',
    //     'file_id': '1o2g3h4i5j6k7l8m9n0o1',
    //     'file_name': 'Example16.txt',
    //     'file_version': '1',
    //     'part_type': '3. Blade Enclosure Chassis',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'CD223344',
    //     'file_id': '2p3h4i5j6k7l8m9n0o1p2',
    //     'file_name': 'Example17.txt',
    //     'file_version': '2',
    //     'part_type': '4. Blade Module Chassis',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'EF445566',
    //     'file_id': '3q4i5j6k7l8m9n0o1p2q3',
    //     'file_name': 'Example18.txt',
    //     'file_version': '3',
    //     'part_type': '5. Blade Server Enclosure',
    //     'file_category': 'BIOS',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'GH667788',
    //     'file_id': '4r5j6k7l8m9n0o1p2q3r4',
    //     'file_name': 'Example19.txt',
    //     'file_version': '1',
    //     'part_type': '1. Air Shroud',
    //     'file_category': 'Regular',
    //     'file_type': 'application/octet-stream',
    // },
    // {
    //     'part_no': 'IJ889900',
    //     'file_id': '5s6k7l8m9n0o1p2q3r4s5',
    //     'file_name': 'Example20.txt',
    //     'file_version': '2',
    //     'part_type': '3. Blade Enclosure Chassis',
    //     'file_category': 'BOM',
    //     'file_type': 'application/octet-stream',
    // },
]