export const SelectOptionsList = {
    partType: [
        '1. Air Shroud',
        '2. Blade Dummy Chassis',
        '3. Blade Enclosure Chassis',
        '4. Blade Module Chassis',
        '5. Blade Server Enclosure',
        '6. Chassis Accessory Box',
        '7. Cable',
        '8. Chassis Parts',
        '9. CD-ROM and accessory',
        '10. Chassis',
        '11. Virtual Chassis',
        '12. Disk Set',
        '13. Cooling Fan',
        '14. Floppy Disk and accessory',
        '15. Cooling Fan accessory',
        '16. Liquid Cooling Solution',
        '17. Micro Blade Dummy Chassis',
        '18. Micro Blade Enclosure Chassis',
        '19. Micro Blade Module Chassis',
        '20. Manual',
        '21. Monitor',
        '22. Mobile Rack',
        '23. OEM Chassis',
        '24. Others',
        '25. Power Supply and accessory',
        '26. SuperBarebones',
        '27. Heat Sink',
        '28. Rack',
        '29. Front Bezel',
        '30. Front Panel(Elec. Device)',
        '31. Tray',
        '32. Label',
        '33. Packaging',
        '34. Rails',
        '35. Add-on Card',
        '36. HD Backplane',
        '37. Control Board',
        '38. CPU',
        '39. Driver',
        '40. DVD Drive',
        '41. GPU',
        '42. Hard Drive',
        '43. Hard Drive Solid State',
        '44. Internal Firmware',
        '45. Motherboard',
        '46. Memory',
        '47. OEM Servers',
        '48. Riser Card',
        '49. SuperBladeSystem',
        '50. Storage Controller Card',
        '51. Solid State Flash Appliance',
        '52. SuperRackSystem',
        '53. SSD-Solid State',
        '54. Switch Ethernet',
        '55. IBM Power System',
        '56. SuperStoreSystem',
        '57. SuperServers',
        '58. Software',
        '59. SuperWorkStations',
        '60. Auto-Configurator System',
        '61. A+ Servers',
        '62. Bracket',
        '63. Blade Server Module',
        '64. Consigned Part',
        '65. Drawings',
        '66. MicroBlade',
        '67. Micro Blade Server Enclosure',
        '68. Micro Blade Server Module',
        '69. OEM Part',
        '70. Power Distributor',
        '71. PIO System',
        '72. Part',
        '73. RKS System',
        '74. Rear Window',
        '75. Retention Modules',
        '76. SuperValue',
        '77. Services',
        '78. Transceiver',
        '79. Non-Manual Related Docs',
    ],
    fileCategory: ['Regular', 'BOM', 'BIOS', 'EEPROM', 'BMC Firmware', 'VRM Firmware', 'CPLD', 'SBOM', 'Other']
}
